---
name: 📦 Build iPXE
on: [push]
jobs:
  build-raspi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build iPXE
        run: docker-compose run --rm ipxe

      - name: Upload iPXE binaries
        uses: actions/upload-artifact@v2
        with:
          name: iPXE binary
          path: output/ipxe.efi

      - name: Create Release and Attach Artifacts
        uses: softprops/action-gh-release@v1
        # run only on tags
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/ipxe.efi
          prerelease: true
